# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: 
      - main

jobs:
  build-and-push-image:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 5

    env:
      REGISTRY: ghcr.io
      TARGET: ${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application
        uses: ./.github/actions/build-image
        with:
          target: '${{ env.REGISTRY }}/oscarligthart/sessions-actions-app'
          file: 'Dockerfile'
